# model setting
enc_layers: 2
dec_layers: 4
dim_feedforward: 1024
num_queries: 40 # 40

# data setting
dataset_name: thumos14
feature: i3d2s
feature_dim: 2048
online_slice: True
slice_len: 128
slice_overlap: 0.75
test_slice_overlap: 0.25

epochs: 80 # 16
lr_step: [50, 70] # [14]

postproc_rank: 1 # 1
postproc_cls_topk: 1 # 1
postproc_ins_topk: 200 # 200
nms_thr: 0.4 # 0.4

act_reg: False
aux_loss: True

use_KK: True
use_QQ: True

use_dn: True

KK_loss_coef: 5.0
QQ_loss_coef: 5.0

# output
output_dir: outputs/thumos14_i3d2s_tadtr