# model setting
enc_layers: 2
dec_layers: 4
dim_feedforward: 1024
#num_queries: 40 # 40
num_queries_enc: -1 # -1
num_queries_one2one: 40 # 40
num_queries_one2many: 167 # 167

# data setting
dataset_name: thumos14
feature: i3d2s
feature_dim: 2048
online_slice: True
slice_len: 128 # 128
slice_overlap: 0.75 # 0.75
test_slice_overlap: 0.25 # 0.25

batch_size: 16 # 16
epochs: 120 # 120, 16
lr_step: [80, 100] # [80, 100], [14]
#lr_step : [14]

postproc_rank: 1 # 1
postproc_cls_topk: 1 # 1
postproc_ins_topk: 200 # 200
nms_thr: 0.4 # 0.4

act_reg: False
aux_loss: True

# use_QK: True
use_KK: True
use_QQ: True

use_dn: False

# QK_loss_coef: 2.0
KK_loss_coef: 2.0
QQ_loss_coef: 2.0

k_one2many: 6 # 6
lambda_one2many: 1.0 # 1.0
random_refpoints_xy: True
two_stage: False

# output
output_dir: outputs/thumos14_i3d2s_tadtr