# model setting
enc_layers: 2
dec_layers: 4
dim_feedforward: 1024
num_queries: 40
nheads: 8
activation: 'relu'
seg_refine: True
dropout: 0.1

# data setting
dataset_name: thumos14
feature: i3d2s
feature_dim: 2048
online_slice: True
slice_len: 128
slice_overlap: 0.75
test_slice_overlap: 0.25

epochs: 120
lr_step: [80, 100]

postproc_rank: 1
postproc_cls_topk: 1
postproc_ins_topk: 200
nms_thr: 0.4

aux_loss: True
use_KK: True
use_QQ: True

cls_loss_coef: 2
seg_loss_coef: 5
iou_loss_coef: 2
eos_coef: 0.1
focal_alpha: 0.25
set_cost_class: 6
set_cost_seg: 5
set_cost_iou: 2
lr: 2e-4

optimizer: 'AdamW'
batch_size: 16
weight_decay: 1e-4
clip_max_norm: 0.1

KK_loss_coef: 5.0
QQ_loss_coef: 5.0