# model setting
enc_layers: 2
dec_layers: 4
dim_feedforward: 1024
num_queries: 40 # 40

# data setting
dataset_name: thumos14
feature: i3d2s
feature_dim: 2048
online_slice: True
slice_len: 128
slice_overlap: 0.75
test_slice_overlap: 0.25

epochs: 120 # 16
lr_step: [80, 100] # [14]

set_cost_class: 2  # Class coefficient # 2
set_cost_seg: 5  # Segment L1 coefficient
set_cost_iou: 2  # Segment IoU coefficient

postproc_rank: 1 # 1
postproc_cls_topk: 1 # 1
postproc_ins_topk: 100 # 100
nms_thr: 0.4 # 0.4

act_reg: False
aux_loss: True

use_KK: False
use_QQ: False

KK_loss_coef: 5.0
QQ_loss_coef: 5.0

# output
output_dir: outputs/thumos14_i3d2s_tadtr